# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  go-tests = true
	non-go = true

[[override]]
  # only needed until kubernetes moves to dep or github.com/docker/distribution's latest tag builds with kubernetes.
  name = "github.com/docker/distribution"
  #revision = "master"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  version = "v1.2.0"
  name = "github.com/digitalocean/godo"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.1"
